AWSTemplateFormatVersion: '2010-09-09'
Description: 'Low-cost CloudFormation template for PewPew game deployment'

Parameters:
  ProjectName:
    Type: String
    Default: pewpew
    Description: Project name for resource naming
  
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  BackendImageUri:
    Type: String
    Default: ''
    Description: ECR URI for backend Docker image. Leave empty initially, will use created ECR repository.
  
  FrontendBuildPath:
    Type: String
    Default: frontend/dist
    Description: Path to frontend build directory
  
  AppRunnerCpu:
    Type: String
    Default: '0.25 vCPU'
    AllowedValues:
      - '0.25 vCPU'
      - '0.5 vCPU'
      - '1 vCPU'
    Description: CPU allocation for App Runner service (0.25 vCPU is cheapest)
  
  AppRunnerMemory:
    Type: String
    Default: '0.5 GB'
    AllowedValues:
      - '0.5 GB'
      - '1 GB'
      - '2 GB'
    Description: Memory allocation for App Runner service (0.5 GB is cheapest)
  
  AppRunnerMinInstances:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 10
    Description: Minimum number of App Runner instances (0 = scale to zero, saves money)
  
  AppRunnerMaxInstances:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 25
    Description: Maximum number of App Runner instances

Conditions:
  HasBackendImageUri: !Not [!Or [!Equals [!Ref BackendImageUri, ''], !Equals [!Ref BackendImageUri, 'placeholder']]]

Resources:
  # ECR Repository for Backend
  BackendECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-backend-${Environment}'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-frontend-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # CloudFront Origin Access Control (OAC) - Replaces deprecated OAI
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-frontend-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: Origin Access Control for frontend S3 bucket

  # S3 Bucket Policy for CloudFront OAC
  # Note: We'll update this after CloudFront distribution is created to include SourceArn condition
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontDistribution
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${ProjectName} frontend distribution'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100  # Use only North America and Europe (cheapest)
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # IAM Role for App Runner
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-apprunner-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # App Runner Service for Backend
  # Only create if a valid image URI is provided
  BackendAppRunnerService:
    Type: AWS::AppRunner::Service
    Condition: HasBackendImageUri
    Properties:
      ServiceName: !Sub '${ProjectName}-backend-${Environment}'
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Ref BackendImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '8000'
            RuntimeEnvironmentVariables:
              - Name: ENVIRONMENT
                Value: !Ref Environment
              - Name: FEATURE_WS_SNAPSHOT
                Value: 'true'
              - Name: FEATURE_JOIN_CODES
                Value: 'true'
        AutoDeploymentsEnabled: false  # Set to true for automatic deployments
      InstanceConfiguration:
        Cpu: !Ref AppRunnerCpu
        Memory: !Ref AppRunnerMemory
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      AutoScalingConfigurationArn: !If 
        - HasBackendImageUri
        - !Ref AppRunnerAutoScaling
        - !Ref 'AWS::NoValue'
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /api/game/state
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5

  # App Runner Auto Scaling Configuration
  AppRunnerAutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub '${ProjectName}-autoscaling-${Environment}'
      MinSize: !Ref AppRunnerMinInstances
      MaxSize: !Ref AppRunnerMaxInstances
      MaxConcurrency: 100  # Requests per instance

  # Outputs
Outputs:
  FrontendBucketName:
    Description: Name of the S3 bucket for frontend
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendBucket'

  FrontendURL:
    Description: CloudFront distribution URL for frontend
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendURL'

  BackendServiceURL:
    Description: App Runner service URL for backend (only if service was created)
    Condition: HasBackendImageUri
    Value: !GetAtt BackendAppRunnerService.ServiceUrl
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendURL'

  BackendECRRepositoryURI:
    Description: ECR repository URI for backend
    Value: !GetAtt BackendECRRepository.RepositoryUri
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendECRURI'

  DeploymentInstructions:
    Description: Instructions for deploying the application
    Value: !Sub |
      IMPORTANT: App Runner service is only created if BackendImageUri parameter is provided.
      
      If you created the stack without BackendImageUri:
      1. Build and push backend Docker image to ECR:
         aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${BackendECRRepository.RepositoryUri}
         docker build -t ${BackendECRRepository.RepositoryUri}:latest ./backend
         docker push ${BackendECRRepository.RepositoryUri}:latest
      
      2. Update the stack with the image URI:
         aws cloudformation update-stack --stack-name ${AWS::StackName} --use-previous-template --parameters ParameterKey=BackendImageUri,ParameterValue=${BackendECRRepository.RepositoryUri}:latest --capabilities CAPABILITY_NAMED_IAM
      
      If App Runner service already exists:
      3. Update App Runner service with new image:
         SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='${ProjectName}-backend-${Environment}'].ServiceArn" --output text)
         aws apprunner start-deployment --service-arn $SERVICE_ARN
      
      4. Build frontend and upload to S3:
         cd frontend && npm run build
         aws s3 sync dist/ s3://${FrontendBucket} --delete
      
      5. Access your application:
         Frontend: https://${CloudFrontDistribution.DomainName}
         Backend: (Check stack outputs after App Runner service is created)

